# Generated by Django 5.2.11 on 2026-05-26 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0022_account_target_utilization_percent'),
        ('categories', '0003_timeline_models'),
        ('core', '0004_alter_userprofile_phone_e164'),
        ('timeline', '0009_recurringrule_is_bill'),
        ('transactions', '0013_transaction_is_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('due_date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('projected', 'Projected'), ('paid', 'Paid'), ('reconciled', 'Reconciled'), ('missed', 'Missed')], default='projected', max_length=20)),
                ('skipped', models.BooleanField(default=False)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_occurrences', to='accounts.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_occurrences', to='categories.category')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_occurrences', to='core.household')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_occurrences', to='timeline.recurringrule')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_occurrences', to='transactions.transaction')),
            ],
            options={
                'db_table': 'bills_occurrence',
                'ordering': ['due_date', 'name'],
                'indexes': [models.Index(fields=['household', 'month'], name='bills_occur_househo_4b1c42_idx'), models.Index(fields=['household', 'due_date'], name='bills_occur_househo_ae6e70_idx'), models.Index(fields=['status'], name='bills_occur_status_f2ac69_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('rule__isnull', False)), fields=('household', 'rule', 'due_date'), name='uniq_bill_occurrence_rule_due')],
            },
        ),
    ]
