# Generated by Django 5.2.11 on 2026-05-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_recurringrule_autopay_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billoccurrence',
            name='autopay_override',
            field=models.CharField(blank=True, default='', help_text='User override: manual, autopay, or unknown.', max_length=16),
        ),
    ]
