# Generated by Django 5.2.11 on 2026-02-18 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('CHECKING', 'Checking'), ('SAVINGS', 'Savings'), ('CREDIT', 'Credit'), ('CASH', 'Cash'), ('INVESTMENT', 'Investment'), ('RETIREMENT_401K', '401k'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.household')),
            ],
            options={
                'db_table': 'accounts_account',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['household', 'account_type'], name='accounts_ac_househo_e22c8f_idx'), models.Index(fields=['household'], name='accounts_ac_househo_6a25e3_idx')],
            },
        ),
    ]
