# Generated by Django 5.2.12 on 2026-03-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_include_in_forecast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['household', 'position', 'name']},
        ),
    ]
