# Generated by Django 5.2.11 on 2026-05-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_account_preserve_partner_transfer_legs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='preserve_partner_transfer_legs',
            field=models.BooleanField(default=False, help_text="When True, deleting or clearing the counterparty account's leg of a transfer removes only that leg; rows on this account are kept and the transfer link is removed. Use for manual-only / non-Plaid ledgers (e.g. institution not responding)."),
        ),
    ]
