# Generated by Django 5.2.11 on 2026-05-16 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_credit_card_modeling'),
        ('core', '0004_alter_userprofile_phone_e164'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='billing_cycle_end_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Legacy alias for statement_closing_day; kept in sync for older clients.', null=True),
        ),
        migrations.CreateModel(
            name='AccountRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('autopay', 'Autopay'), ('transfer', 'Transfer'), ('savings_funding', 'Savings funding'), ('debt_payment', 'Debt payment'), ('credit_card_payment', 'Credit card payment'), ('loan_payment', 'Loan payment'), ('investment_contribution', 'Investment contribution'), ('bill_funding', 'Bill funding'), ('paycheck_deposit', 'Paycheck deposit'), ('other', 'Other')], db_index=True, max_length=32)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('default_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('one_time', 'One time'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('twice_monthly', 'Twice monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_account', models.ForeignKey(help_text='Account money goes TO.', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='accounts.account')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_relationships', to='core.household')),
                ('source_account', models.ForeignKey(help_text='Account money comes FROM.', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='accounts.account')),
            ],
            options={
                'db_table': 'accounts_account_relationship',
                'ordering': ['household', 'source_account', 'destination_account'],
                'indexes': [models.Index(fields=['household', 'is_active'], name='accounts_ac_househo_b2370e_idx'), models.Index(fields=['source_account', 'destination_account'], name='accounts_ac_source__b79642_idx')],
            },
        ),
    ]
