# Generated by Django 5.2.11 on 2026-05-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_account_lifecycle'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='account',
            new_name='accounts_ac_househo_fc1084_idx',
            old_name='accounts_ac_househo_status_idx',
        ),
        migrations.AlterField(
            model_name='account',
            name='archived',
            field=models.BooleanField(default=False, help_text='Legacy flag; kept in sync with status=archived for older clients.'),
        ),
    ]
