# Generated by Django 5.2.11 on 2026-05-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_account_include_in_available_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='include_in_available_credit',
            field=models.BooleanField(default=True, help_text='When true, this credit card counts toward dashboard Available Credit totals.'),
        ),
    ]
