# Generated by Django 5.2.17 on 2026-09-07 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0025_account_minimum_payment_source_fields'),
        ('core', '0009_userprofile_projected_funds_prefs'),
        ('timeline', '0019_scenario_guided_strategy'),
        ('transactions', '0015_pending_and_manual_import_match_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectedFundsAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_date', models.DateField()),
                ('fingerprint', models.CharField(db_index=True, max_length=220, unique=True)),
                ('alert_type', models.CharField(choices=[('INSUFFICIENT_FUNDS', 'Insufficient funds'), ('CREDIT_LIMIT_RISK', 'Credit limit risk')], max_length=32)),
                ('severity', models.CharField(choices=[('WATCH', 'Watch'), ('AT_RISK', 'At risk'), ('CRITICAL', 'Critical')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('projected_balance_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('projected_balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('shortfall', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payee', models.CharField(blank=True, default='', max_length=255)),
                ('first_detected_at', models.DateTimeField(auto_now_add=True)),
                ('last_evaluated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('notified_3d_at', models.DateTimeField(blank=True, null=True)),
                ('notified_1d_at', models.DateTimeField(blank=True, null=True)),
                ('notified_day_of_at', models.DateTimeField(blank=True, null=True)),
                ('last_notified_shortfall', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projected_funds_alerts', to='accounts.account')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projected_funds_alerts', to='core.household')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projected_funds_alerts', to='timeline.recurringrule')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projected_funds_alerts', to='transactions.transaction')),
            ],
            options={
                'db_table': 'alerts_projected_funds_alert',
                'ordering': ['occurrence_date', 'id'],
                'indexes': [models.Index(fields=['household', 'resolved_at', 'dismissed_at'], name='alerts_proj_househo_11e1d2_idx'), models.Index(fields=['account', 'occurrence_date'], name='alerts_proj_account_8a5b36_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expo_push_token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alerts_push_device',
                'indexes': [models.Index(fields=['user', 'enabled'], name='alerts_push_user_id_103e58_idx')],
            },
        ),
    ]
