# Generated by Django 5.2.17 on 2026-09-06 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=128)),
                ('livemode', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'billing_stripe_webhook_event',
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['event_type', 'processed_at'], name='billing_str_event_t_cad75e_idx')],
            },
        ),
        migrations.CreateModel(
            name='BillingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('FREE', 'Free'), ('PREMIUM', 'Premium')], default='FREE', max_length=16)),
                ('status', models.CharField(default='inactive', help_text='Stripe subscription status, or inactive when no subscription exists.', max_length=32)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_price_id', models.CharField(blank=True, default='', max_length=255)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_subscription',
                'indexes': [models.Index(fields=['plan', 'status'], name='billing_sub_plan_f3f19d_idx'), models.Index(fields=['status'], name='billing_sub_status_948046_idx')],
            },
        ),
    ]
