# Generated by Django 5.2.11 on 2026-02-18 22:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('planned_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='categories.category')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.household')),
            ],
            options={
                'db_table': 'budgets_budget',
                'ordering': ['year', 'month', 'category'],
                'indexes': [models.Index(fields=['household', 'year', 'month'], name='budgets_bud_househo_907f49_idx')],
                'constraints': [models.UniqueConstraint(fields=('household', 'category', 'year', 'month'), name='uniq_household_category_year_month')],
            },
        ),
    ]
