# Generated by Django 5.2.11 on 2026-05-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_set_fixed_target_type_for_recurring'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='spendingtarget',
            new_name='budgets_spe_househo_89bedb_idx',
            old_name='budgets_spe_househo_idx',
        ),
        migrations.RenameIndex(
            model_name='spendingtarget',
            new_name='budgets_spe_househo_8d4afb_idx',
            old_name='budgets_spe_househo_cat_idx',
        ),
        migrations.AlterField(
            model_name='spendingtarget',
            name='target_type',
            field=models.CharField(choices=[('fixed', 'Fixed / scheduled'), ('variable', 'Variable')], default='variable', max_length=20),
        ),
    ]
