# Generated by Django 5.2.17 on 2026-09-05 07:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0024_alter_account_include_in_available_credit'),
        ('core', '0006_userprofile_default_forecast_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='DtiDebtItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('debt_type', models.CharField(choices=[('credit_card', 'Credit card'), ('auto_loan', 'Auto loan'), ('student_loan', 'Student loan'), ('mortgage', 'Mortgage'), ('home_equity', 'Home equity'), ('personal_loan', 'Personal loan'), ('installment_loan', 'Installment loan'), ('alimony', 'Alimony'), ('child_support', 'Child support'), ('other', 'Other')], default='other', max_length=32)),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Authoritative when payment_source=manual. Not overwritten from a linked account.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('outstanding_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('payment_source', models.CharField(choices=[('manual', 'Manual'), ('linked_account_minimum', 'Linked account minimum')], default='manual', max_length=32)),
                ('included', models.BooleanField(default=True)),
                ('months_remaining', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dti_debt_items', to='core.household')),
                ('linked_account', models.ForeignKey(blank=True, help_text='Optional account link. Deleting the account nulls this; the DTI profile remains.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dti_debt_items', to='accounts.account')),
            ],
            options={
                'db_table': 'affordability_dti_debt_item',
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['household', 'position'], name='affordabili_househo_754c3f_idx'), models.Index(fields=['household', 'linked_account'], name='affordabili_househo_f8de10_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('monthly_payment__gte', 0)), name='dti_debt_payment_nonnegative'), models.CheckConstraint(condition=models.Q(('outstanding_balance__isnull', True), ('outstanding_balance__gte', 0), _connector='OR'), name='dti_debt_balance_nonnegative'), models.CheckConstraint(condition=models.Q(('months_remaining__isnull', True), ('months_remaining__gt', 0), _connector='OR'), name='dti_debt_months_remaining_positive'), models.UniqueConstraint(condition=models.Q(('linked_account__isnull', False)), fields=('household', 'linked_account'), name='uniq_dti_debt_linked_account_per_household')],
            },
        ),
        migrations.CreateModel(
            name='DtiIncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gross_monthly_amount', models.DecimalField(decimal_places=2, help_text='Gross monthly amount. Inclusion is user-controlled; type is a label only.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('income_type', models.CharField(choices=[('employment', 'Employment'), ('self_employment', 'Self-employment'), ('contract', 'Contract'), ('rental', 'Rental'), ('retirement', 'Retirement'), ('social_security', 'Social Security'), ('disability', 'Disability'), ('alimony', 'Alimony'), ('child_support', 'Child support'), ('other', 'Other')], default='other', help_text='Organizational label only. Does not decide lender-qualifying status.', max_length=32)),
                ('included', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dti_income_sources', to='core.household')),
            ],
            options={
                'db_table': 'affordability_dti_income_source',
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['household', 'position'], name='affordabili_househo_dfe089_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('gross_monthly_amount__gte', 0)), name='dti_income_amount_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='DtiProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_back_end_dti_percent', models.DecimalField(decimal_places=2, default=Decimal('36.00'), help_text='Planning default for back-end DTI (%). User-editable; not an approval limit.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('target_front_end_dti_percent', models.DecimalField(blank=True, decimal_places=2, default=Decimal('28.00'), help_text='Optional planning default for front-end DTI (%). Not an approval limit.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('current_housing_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saved current monthly housing payment (rent or mortgage PITI, etc.).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('current_housing_label', models.CharField(blank=True, default='', max_length=255)),
                ('include_current_housing_in_current_dti', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dti_profile', to='core.household')),
            ],
            options={
                'db_table': 'affordability_dti_profile',
                'constraints': [models.CheckConstraint(condition=models.Q(('current_housing_payment__gte', 0)), name='dti_profile_housing_nonnegative'), models.CheckConstraint(condition=models.Q(('target_back_end_dti_percent__gt', 0), ('target_back_end_dti_percent__lte', 100)), name='dti_profile_back_end_target_range'), models.CheckConstraint(condition=models.Q(('target_front_end_dti_percent__isnull', True), models.Q(('target_front_end_dti_percent__gt', 0), ('target_front_end_dti_percent__lte', 100)), _connector='OR'), name='dti_profile_front_end_target_range')],
            },
        ),
    ]
