# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="category", name="uniq_household_parent_name"),
        migrations.RemoveIndex(model_name="category", name="categories__househo_86adb5_idx"),
        migrations.RenameField(model_name="category", old_name="order", new_name="sort_order"),
        migrations.AddField(
            model_name="category",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["household", "category_type", "is_archived"],
                name="categories__househo_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["household", "name"], name="categories__househo_name_idx"),
        ),
    ]
