# Generated by Django 5.2.11 on 2026-02-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_add_archive_and_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_type', 'sort_order', 'name']},
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='categories__househo_51550f_idx',
            old_name='categories__househo_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='categories__househo_57be12_idx',
            old_name='categories__househo_name_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
