# Generated by Django 5.2.11 on 2026-08-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_dedupe_and_unique_category'),
        ('core', '0006_userprofile_default_forecast_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='system_code',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['household', 'system_code'], name='categories__househo_c42940_idx'),
        ),
    ]
