# Generated by Django 5.2.17 on 2026-09-07 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_id', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('dismissed', 'Dismissed'), ('snoozed', 'Snoozed')], max_length=16)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendations_preference',
                'indexes': [models.Index(fields=['user', 'state'], name='recommendat_user_id_d297e3_idx'), models.Index(fields=['user', 'recommendation_id'], name='recommendat_user_id_12b98a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'recommendation_id'), name='uniq_recommendation_pref_user_id')],
            },
        ),
    ]
