export const REVIEW_PROMPT_COPY = {
  enjoymentTitle: "Enjoying FlowSight?",
  enjoymentBody: "We’d love to know how your experience has been so far.",
  yesLabel: "Yes, I’m enjoying FlowSight",
  noLabel: "No, I’m not enjoying FlowSight",
  notNowLabel: "Not now",
  reviewTitle: "Would you leave FlowSight a review?",
  reviewBody: "Reviews help other people discover FlowSight.",
  leaveReviewLabel: "Leave a review",
  maybeLaterLabel: "Maybe later",
  feedbackTitle: "Tell us what we can improve",
  feedbackBody: "We’d really appreciate your feedback.",
  feedbackPlaceholder: "What’s not working well?",
  feedbackCategoryLabel: "Category (optional)",
  contactLabel: "May we contact you about this?",
  contactHint: (email: string) => `We’ll use ${email}`,
  submitLabel: "Send feedback",
  thanksTitle: "Thanks for the feedback.",
  thanksBody: "We appreciate you helping us improve FlowSight.",
  doneLabel: "Done",
} as const;
