# Generated by Django 5.2.13 on 2026-04-28 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_link', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='plaiditem',
            new_name='plaid_link__househo_d44a1e_idx',
            old_name='plaid_link_p_househo_idx',
        ),
    ]
