# Generated by Django 5.2.15 on 2026-06-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_link', '0003_plaidlinkedaccount_mask'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaiditem',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, help_text='When transactions were last imported from Plaid for this login.', null=True),
        ),
    ]
