# Generated by Django 5.2.11 on 2026-05-26 21:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0022_account_target_utilization_percent'),
        ('core', '0004_alter_userprofile_phone_e164'),
        ('timeline', '0008_recurringrule_paused_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('goal_type', models.CharField(choices=[('savings', 'Savings'), ('debt_payoff', 'Debt payoff'), ('emergency_fund', 'Emergency fund'), ('house_down_payment', 'House down payment'), ('college', 'College'), ('vacation', 'Vacation'), ('taxes', 'Taxes'), ('car', 'Car'), ('custom', 'Custom')], default='savings', max_length=32)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('starting_debt_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Baseline debt for payoff goals; defaults to owed balance at creation.', max_digits=15, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('priority', models.PositiveSmallIntegerField(default=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='active', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('contribution_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_goals', to='timeline.recurringrule')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_goals', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_goals', to='core.household')),
                ('linked_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_goals', to='accounts.account')),
                ('linked_credit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_goals', to='accounts.account')),
            ],
            options={
                'db_table': 'goals_financial_goal',
                'ordering': ['priority', '-created_at'],
                'indexes': [models.Index(fields=['household', 'status'], name='goals_finan_househo_90a138_idx'), models.Index(fields=['household', 'priority'], name='goals_finan_househo_c7b3f8_idx')],
            },
        ),
    ]
