# Generated by Django 5.2.11 on 2026-05-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_migrate_financial_goals_to_buckets'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='financialgoal',
            name='goals_finan_househo_90a138_idx',
        ),
        migrations.RemoveIndex(
            model_name='financialgoal',
            name='goals_finan_househo_c7b3f8_idx',
        ),
        migrations.RenameIndex(
            model_name='goalbucket',
            new_name='goals_goal__househo_01770a_idx',
            old_name='goals_goal__househo_idx',
        ),
        migrations.RenameIndex(
            model_name='goalbucket',
            new_name='goals_goal__linked__d9840d_idx',
            old_name='goals_goal__linked__idx',
        ),
        migrations.RenameIndex(
            model_name='goalcontribution',
            new_name='goals_goal__bucket__5eec10_idx',
            old_name='goals_goal__bucket__idx',
        ),
        migrations.RenameIndex(
            model_name='goalcontribution',
            new_name='goals_goal__account_94ca9a_idx',
            old_name='goals_goal__account_idx',
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='starting_debt_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='goalbucket',
            name='include_in_safe_to_spend',
            field=models.BooleanField(default=True, help_text='When true, allocated amount reduces safe-to-spend on the linked account.'),
        ),
        migrations.AlterField(
            model_name='ruleallocation',
            name='percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percent of rule amount (0-100).', max_digits=6, null=True),
        ),
    ]
