# Generated by Django 5.2.11 on 2026-02-26 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_add_starting_balance_apr'),
        ('categories', '0003_timeline_models'),
        ('core', '0002_add_default_account'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('MONTHLY_DAY', 'Monthly (day of month)'), ('MONTHLY_NTH_WEEKDAY', 'Monthly (nth weekday)'), ('YEARLY', 'Yearly')], max_length=30)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='0=Monday .. 6=Sunday (ISO weekday - 1)', null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nth_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_rules', to='accounts.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_rules', to='categories.category')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_rules', to='core.household')),
            ],
            options={
                'db_table': 'timeline_recurring_rule',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='core.household')),
            ],
            options={
                'db_table': 'timeline_scenario',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioRuleOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('override_active', models.BooleanField(blank=True, null=True)),
                ('override_start_date', models.DateField(blank=True, null=True)),
                ('override_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('override_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account')),
                ('override_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='categories.category')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_overrides', to='timeline.recurringrule')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_overrides', to='timeline.scenario')),
            ],
            options={
                'db_table': 'timeline_scenario_rule_override',
            },
        ),
        migrations.CreateModel(
            name='StatementTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_date', models.DateField()),
                ('description', models.CharField(max_length=512)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_transactions', to='accounts.account')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_transactions', to='core.household')),
            ],
            options={
                'db_table': 'timeline_statement_transaction',
                'ordering': ['posted_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('UNMATCHED', 'Unmatched')], max_length=20)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('matched_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_matches', to='transactions.transaction')),
                ('statement_txn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='timeline.statementtransaction')),
            ],
            options={
                'db_table': 'timeline_reconciliation_match',
            },
        ),
        migrations.AddIndex(
            model_name='recurringrule',
            index=models.Index(fields=['household', 'active'], name='timeline_re_househo_1ecf14_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringrule',
            index=models.Index(fields=['account'], name='timeline_re_account_e7fd7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='scenarioruleoverride',
            constraint=models.UniqueConstraint(fields=('scenario', 'rule'), name='uniq_scenario_rule'),
        ),
        migrations.AddIndex(
            model_name='statementtransaction',
            index=models.Index(fields=['account', 'posted_date'], name='timeline_st_account_a7c398_idx'),
        ),
        migrations.AddIndex(
            model_name='statementtransaction',
            index=models.Index(fields=['household'], name='timeline_st_househo_9ebc67_idx'),
        ),
    ]
