# Generated by Django 5.2.11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_starting_balance_apr"),
        ("timeline", "0001_timeline_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringrule",
            name="transfer_to_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurring_rules_receiving",
                to="accounts.account",
            ),
        ),
    ]
