# Generated by Django 5.2.11 on 2026-03-02 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_credit_limit'),
        ('core', '0002_add_default_account'),
        ('timeline', '0002_recurring_rule_transfer_to_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringrule',
            name='transfer_to_account',
            field=models.ForeignKey(blank=True, help_text='When set, this rule is a transfer: outflow from account, inflow to this account (e.g. credit card payment).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_rules_receiving', to='accounts.account'),
        ),
        migrations.CreateModel(
            name='UpcomingChargeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(help_text='Date when the charge is scheduled to be paid.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_charge_notifications', to='core.household')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_notifications', to='timeline.recurringrule')),
            ],
            options={
                'db_table': 'timeline_upcoming_charge_notification',
                'ordering': ['due_date', 'created_at'],
                'indexes': [models.Index(fields=['household', 'read_at'], name='timeline_up_househo_63b646_idx')],
                'constraints': [models.UniqueConstraint(fields=('household', 'rule', 'due_date'), name='uniq_upcoming_charge_household_rule_due')],
            },
        ),
    ]
