# Generated by Django (manual)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0003_upcoming_charge_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringRuleSkip",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("rule", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="skipped_occurrences", to="timeline.recurringrule")),
            ],
            options={
                "db_table": "timeline_recurring_rule_skip",
            },
        ),
        migrations.AddConstraint(
            model_name="recurringruleskip",
            constraint=models.UniqueConstraint(fields=("rule", "date"), name="uniq_rule_skip_rule_date"),
        ),
    ]
