# Generated by Django 5.2.12 on 2026-03-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_recurringruleskip'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recurringruleskip',
            index=models.Index(fields=['rule', 'date'], name='timeline_re_rule_id_21894a_idx'),
        ),
    ]
