# Generated by Django 5.2.11 on 2026-04-02 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_account_archived'),
        ('timeline', '0005_recurringruleskip_timeline_re_rule_id_21894a_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestCycleSkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_cycle_skips', to='accounts.account')),
            ],
            options={
                'db_table': 'timeline_interest_cycle_skip',
                'indexes': [models.Index(fields=['account', 'cycle_end_date'], name='timeline_in_account_9b5ad6_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'cycle_end_date'), name='uniq_interest_skip_account_cycle')],
            },
        ),
    ]
