# Generated by Django 5.2.11 on 2026-05-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0008_recurringrule_paused_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringrule',
            name='is_bill',
            field=models.BooleanField(default=False, help_text='Include this rule on the monthly bill checklist (also inferred from direction/category).'),
        ),
    ]
