# Generated by Django 5.2.11 on 2026-05-28 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0011_recurringrule_payment_flexibility_days'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scenarioonetimeevent',
            new_name='timeline_sc_scenari_22e7a2_idx',
            old_name='timeline_sc_scenario_0a8f2d_idx',
        ),
    ]
