# Generated by Django 5.2.11 on 2026-05-29 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0014_scenario_added_recurring'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scenarioaddedrecurring',
            new_name='timeline_sc_scenari_e6b5ec_idx',
            old_name='timeline_sc_scenari_added_idx',
        ),
    ]
