# Generated by Django 5.2.11 on 2026-05-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0017_recurringruleschedule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recurringruleschedule',
            new_name='timeline_re_rule_id_4d6ee2_idx',
            old_name='timeline_ru_rule_id_eff_idx',
        ),
        migrations.AlterField(
            model_name='recurringruleschedule',
            name='direction',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recurringruleschedule',
            name='frequency',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('MONTHLY_DAY', 'Monthly (day of month)'), ('MONTHLY_NTH_WEEKDAY', 'Monthly (nth weekday)'), ('YEARLY', 'Yearly')], max_length=30),
        ),
    ]
