# Generated by Django 5.2.17 on 2026-09-05 01:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_account_include_in_available_credit'),
        ('timeline', '0018_rename_timeline_ru_rule_id_eff_idx_timeline_re_rule_id_4d6ee2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioGuidedStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_type', models.CharField(choices=[('debt_first_vs_save_first', 'Debt first vs. save first')], default='debt_first_vs_save_first', max_length=64)),
                ('start_date', models.DateField()),
                ('minimum_cash_buffer', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('allocation_percent', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                ('payoff_strategy', models.CharField(choices=[('avalanche', 'Avalanche'), ('snowball', 'Snowball'), ('utilization_target', 'Utilization target'), ('custom', 'Custom')], default='avalanche', max_length=32)),
                ('resume_savings_after_payoff', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('included_debt_accounts', models.ManyToManyField(blank=True, related_name='guided_strategies_as_debt', to='accounts.account')),
                ('savings_account', models.ForeignKey(help_text='Savings/cash destination of the selected transfer rules.', on_delete=django.db.models.deletion.PROTECT, related_name='guided_strategies_as_savings', to='accounts.account')),
                ('savings_transfer_rules', models.ManyToManyField(blank=True, related_name='guided_strategies_as_savings_transfer', to='timeline.recurringrule')),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guided_strategy', to='timeline.scenario')),
                ('source_account', models.ForeignKey(help_text='Cash/asset account whose surplus may be reallocated.', on_delete=django.db.models.deletion.PROTECT, related_name='guided_strategies_as_source', to='accounts.account')),
            ],
            options={
                'db_table': 'timeline_scenario_guided_strategy',
            },
        ),
        migrations.CreateModel(
            name='ScenarioGuidedDebtPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(help_text='1-based payoff order. Lower values are paid first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guided_strategy_debt_priorities', to='accounts.account')),
                ('guided_strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_priorities', to='timeline.scenarioguidedstrategy')),
            ],
            options={
                'db_table': 'timeline_scenario_guided_debt_priority',
                'ordering': ['priority', 'id'],
                'indexes': [models.Index(fields=['guided_strategy', 'priority'], name='timeline_sc_guided__ccd2b6_idx')],
                'constraints': [models.UniqueConstraint(fields=('guided_strategy', 'account'), name='uniq_guided_strategy_debt_acct'), models.UniqueConstraint(fields=('guided_strategy', 'priority'), name='uniq_guided_strategy_debt_prio')],
            },
        ),
    ]
