# Generated by Django 5.2.11 on 2026-02-26 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_timeline_models'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='timeline.recurringrule'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='timeline.scenario'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('ACTUAL', 'Actual'), ('RULE', 'From rule'), ('ONE_TIME', 'One-time planned')], default='ACTUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('CLEARED', 'Cleared'), ('RECONCILED', 'Reconciled')], default='CLEARED', max_length=20),
        ),
    ]
