# Generated by Django 5.2.11 on 2026-04-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_timeline_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('ACTUAL', 'Actual'), ('RULE', 'From rule'), ('ONE_TIME', 'One-time planned'), ('INTEREST', 'Projected interest')], default='ACTUAL', max_length=20),
        ),
    ]
