# Generated by Django 5.2.11 on 2026-04-02 19:25

from collections import defaultdict

from django.db import migrations, models


def interest_anchor_forwards(apps, schema_editor):
    Transaction = apps.get_model("transactions", "Transaction")
    for row in Transaction.objects.filter(
        source="INTEREST", interest_cycle_end_date__isnull=True
    ).iterator(chunk_size=200):
        Transaction.objects.filter(pk=row.pk).update(interest_cycle_end_date=row.date)
    pks_by_key = defaultdict(list)
    for row in Transaction.objects.filter(source="INTEREST").values(
        "id", "account_id", "interest_cycle_end_date"
    ):
        anchor = row["interest_cycle_end_date"]
        if anchor is None:
            continue
        pks_by_key[(row["account_id"], anchor)].append(row["id"])
    for _key, pks in pks_by_key.items():
        if len(pks) <= 1:
            continue
        pks.sort()
        for pk in pks[1:]:
            Transaction.objects.filter(pk=pk).delete()


def interest_anchor_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_account_archived'),
        ('categories', '0003_timeline_models'),
        ('timeline', '0005_recurringruleskip_timeline_re_rule_id_21894a_idx'),
        ('transactions', '0003_add_interest_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='interest_cycle_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'interest_cycle_end_date'], name='transaction_account_6d3a2e_idx'),
        ),
        migrations.RunPython(interest_anchor_forwards, interest_anchor_reverse),
    ]
