# Generated by Django 5.2.11 on 2026-04-29 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_account_last_four'),
        ('categories', '0003_timeline_models'),
        ('core', '0004_alter_userprofile_phone_e164'),
        ('timeline', '0006_interest_cycle_skip'),
        ('transactions', '0005_transaction_plaid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='import_match_status',
            field=models.CharField(choices=[('NONE', 'Not applicable'), ('UNMATCHED', 'Imported, unmatched'), ('SUGGESTED', 'Suggestions pending'), ('MATCHED', 'Matched to planned'), ('IGNORED', 'Ignored import'), ('DUPLICATE', 'Duplicate import')], db_index=True, default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='imported_description',
            field=models.TextField(blank=True, default='', help_text='Raw bank/import description (e.g. Plaid name).'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='normalized_payee',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='transaction',
            name='planned_date',
            field=models.DateField(blank=True, help_text='User-intended date for planned rows; falls back to date.', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='posted_date',
            field=models.DateField(blank=True, help_text='Bank posted date when known (e.g. from Plaid); defaults to date for display.', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('ACTUAL', 'Actual'), ('RULE', 'From rule'), ('ONE_TIME', 'One-time planned'), ('INTEREST', 'Projected interest'), ('PLAID', 'Imported from Plaid'), ('SYSTEM', 'System')], default='ACTUAL', max_length=20),
        ),
        migrations.CreateModel(
            name='MatchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_suggestions', to='transactions.transaction')),
                ('planned_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_import_matches', to='transactions.transaction')),
            ],
            options={
                'db_table': 'transactions_match_suggestion',
            },
        ),
        migrations.CreateModel(
            name='TransactionMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('SAME_ACCOUNT', 'Same account'), ('TRANSFER_SOURCE', 'Transfer source leg'), ('TRANSFER_DEST', 'Transfer destination leg'), ('MANUAL', 'Manual link')], default='SAME_ACCOUNT', max_length=32)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('confidence', models.CharField(choices=[('AUTO', 'Auto-matched'), ('SUGGESTED', 'User confirmed suggestion'), ('MANUAL', 'User manual match')], default='AUTO', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_as_imported', to='transactions.transaction')),
                ('planned_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_as_planned', to='transactions.transaction')),
            ],
            options={
                'db_table': 'transactions_transaction_match',
            },
        ),
        migrations.CreateModel(
            name='TransferGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive payment/transfer amount.', max_digits=15)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('PARTIALLY_MATCHED', 'Partially matched'), ('MATCHED', 'Matched'), ('CLEARED', 'Cleared'), ('CANCELED', 'Canceled')], default='PLANNED', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_groups_created', to=settings.AUTH_USER_MODEL)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_groups_from', to='accounts.account')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_groups', to='core.household')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_groups_to', to='accounts.account')),
            ],
            options={
                'db_table': 'transactions_transfer_group',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.transfergroup'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['import_match_status', 'account'], name='transaction_import__d3982b_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchsuggestion',
            constraint=models.UniqueConstraint(fields=('imported_transaction', 'planned_transaction'), name='uniq_match_suggestion_pair'),
        ),
        migrations.AddConstraint(
            model_name='transactionmatch',
            constraint=models.UniqueConstraint(fields=('planned_transaction',), name='uniq_txn_match_planned'),
        ),
        migrations.AddConstraint(
            model_name='transactionmatch',
            constraint=models.UniqueConstraint(fields=('imported_transaction',), name='uniq_txn_match_imported'),
        ),
        migrations.AddIndex(
            model_name='transfergroup',
            index=models.Index(fields=['household', 'scheduled_date'], name='transaction_househo_522f99_idx'),
        ),
        migrations.AddIndex(
            model_name='transfergroup',
            index=models.Index(fields=['from_account', 'to_account', 'scheduled_date'], name='transaction_from_ac_2ff8db_idx'),
        ),
    ]
