# Generated by Django 5.2.11 on 2026-05-13 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_account_preserve_partner_transfer_legs'),
        ('transactions', '0006_transfer_groups_and_matching'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_current_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('app_current_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('last_reconciled_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('final_reconciled_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='accounts.account')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions_reconciliation',
                'ordering': ['-completed_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='reconciliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.reconciliation'),
        ),
        migrations.AddIndex(
            model_name='reconciliation',
            index=models.Index(fields=['account', '-completed_at'], name='transaction_account_c552df_idx'),
        ),
    ]
