# Generated by Django 5.2.11 on 2026-05-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_reconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliation',
            name='period_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='period_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
