# Generated by Django 5.2.11 on 2026-05-16 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_account_relationships'),
        ('transactions', '0009_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfergroup',
            name='relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_groups', to='accounts.accountrelationship'),
        ),
    ]
