# Generated by Django 5.2.11 on 2026-05-26 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_reconciliation_history'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reconciliation',
            new_name='transaction_account_4089cd_idx',
            old_name='transaction_account_8a1f0d_idx',
        ),
    ]
