# Generated by Django 5.2.11 on 2026-05-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_rename_transaction_account_8a1f0d_idx_transaction_account_4089cd_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_bill',
            field=models.BooleanField(default=False, help_text='Treat this transaction as a bill on the monthly checklist.'),
        ),
    ]
