# Generated by Django 5.2.11 on 2026-06-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_account_include_in_available_credit'),
        ('categories', '0004_dedupe_and_unique_category'),
        ('timeline', '0018_rename_timeline_ru_rule_id_eff_idx_timeline_re_rule_id_4d6ee2_idx_and_more'),
        ('transactions', '0013_transaction_is_bill'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['rule', 'account', 'date'], name='txn_rule_acct_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['rule', 'date', 'source'], name='txn_rule_date_src_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'source', 'date'], name='txn_acct_src_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'reconciled', 'date'], name='txn_acct_recon_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'source', 'import_match_status'], name='txn_acct_src_match_idx'),
        ),
    ]
