# Generated by Django 5.2.11 on 2026-07-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_account_include_in_available_credit'),
        ('categories', '0004_dedupe_and_unique_category'),
        ('timeline', '0018_rename_timeline_ru_rule_id_eff_idx_timeline_re_rule_id_4d6ee2_idx_and_more'),
        ('transactions', '0014_transaction_forecast_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_pending',
            field=models.BooleanField(default=False, help_text='True while the bank/Plaid transaction is still pending (not yet posted).'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pending_transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='Plaid pending_transaction_id linking a posted import to its prior pending row.', max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'amount', 'date'], name='txn_acct_amt_date_idx'),
        ),
    ]
