# Generated by Django 5.2.13 on 2026-04-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_phone_e164'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_e164',
            field=models.CharField(blank=True, default='', help_text='Mobile E.164 for Plaid Link (e.g. +15204615387).', max_length=20),
        ),
    ]
