# Generated by Django 5.2.13 on 2026-08-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_userprofile_phone_e164"),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="financial_revision",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Incremented on mutations that change balances or forecasts.",
            ),
        ),
    ]
