# Generated by Django 5.2.13 on 2026-08-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_household_financial_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="default_forecast_days",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (30, "30 days"),
                    (60, "60 days"),
                    (90, "90 days"),
                    (180, "6 months"),
                ],
                default=30,
                help_text="Default Forecast Window for Dashboard, Action Center, and Transactions.",
            ),
        ),
    ]
